Adds Modified Readme file
INF6420/ss23-Molly872 pull request #2
Opened 2023-05-18 01:29 UTC by Molly872

2023-05-18 12:37 UTC, axamei requested changes

2023-05-18 12:37 UTC, axamei commented on README.md
> +![](WireFrames\About-Me-Page-Wireframe.png)
Please change `\` to `/`

2023-05-18 12:37 UTC, axamei commented on README.md
> +![](WireFrames\Book-List-(Landing-Page)-Wireframe.png)
Please change `\` to `/`

2023-05-18 12:37 UTC, axamei commented on README.md
> +![](WireFrames\Book-Review-Ind-Book-Wireframe.png)
Please change `\` to `/`

2023-05-18 12:37 UTC, axamei commented on README.md
> +![](WireFrames\Make-A-Recommendation-Page-Wireframe.png)
Please change `\` to `/`

2023-05-20 02:51 UTC, Molly872 commented on README.md
> +![](WireFrames\About-Me-Page-Wireframe.png)
Updated.  Let me know if you don't see it

2023-05-20 02:52 UTC, Molly872 commented on README.md
> +![](WireFrames\Book-List-(Landing-Page)-Wireframe.png)
Updated. Thanks!

2023-05-20 02:52 UTC, Molly872 commented on README.md
> +![](WireFrames\Book-Review-Ind-Book-Wireframe.png)
Updated, thanks!

2023-05-20 02:52 UTC, Molly872 commented on README.md
> +![](WireFrames\Make-A-Recommendation-Page-Wireframe.png)
updated, thanks!

2023-05-22 17:34 UTC, axamei commented
@Molly872 I don't see the change. Can you make sure your changes are committed and then pushed? Book an appointment if you need clarity.

2023-05-24 12:26 UTC, axamei approved these changes

2023-05-24 12:26 UTC, merged